---
name: Build Release

on:
  workflow_dispatch:
  release:
    types: [published]
#  schedule:
#    - cron: "0 10 1 * *" # Update the image every first day of a month at 10am to provide regular updates
  push:
    tags:
      - '*'
#    branches:
#    - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout latest release
        run: git checkout $(git describe --tags `git rev-list --tags --max-count=1`) -b latest-release
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            mrmoe/moe-traccar
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: ghcr.io

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

          # push: true
          # tags: mrmoe/moe-hugo:latest, 
          #   ghcr.io/moeb98/moe-hugo:latest,
          #   mrmoe/moe-hugo:$(git describe --tags `git rev-list --tags --max-count=1`),
          #   ghcr.io/moeb98/moe-hugo:$(git describe --tags `git rev-list --tags --max-count=1`)







